language: groovy

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_bb9481c64672_key -iv $encrypted_bb9481c64672_iv -in secrets.properties.enc -out secrets.properties -d

install: ./gradlew assemble --stacktrace

after_success: ./gradlew artifactoryPublish
